# Generated by Django 5.2.5 on 2025-09-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='c_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
